openapi: 3.0.1
info:
  title: API Palabras
  description: API que permite convertir un modificar un texto ajustando sus letras en mayúsculas y minúsculas, según sea el caso
  termsOfService: ''
  contact:
    name: Saul Ricardo Tarazona García
    email: saul.tarazona@segurosbolivar.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api/v1/palabras
    description: Servidor de Desarrollo no HTTPS
paths:
  /textoAjustado:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando la primera letra de cada palabra y los espacios
      operationId: ajustarTexto1MayusculaDemasMinuscula
      description: Ajusta el texto modificando la primera letra de cada palabra en mayúscula, y cambiando los espacios entre palabras por el valor del token indicado
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
        - in: query
          name: token
          description: Valor por el que serán remplazados los espacios entre palabras
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /invertido:
    post:
      tags:
        - palabras
      summary: Ajusta el texto cambiando mayúsculas por minúsculas
      operationId: intercalarMayusculasMinusculas
      description: Ajusta el texto modificando las letras en mayúscula por minúscula, y viceversa
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /primeraLetra:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando la primera letra de cada palabra
      operationId: cambiarLetra1DemasDiferenteALetra1
      description: Ajusta el texto modificando la primera letra de cada palabra, pasándola de mayúscula a minúscula o viceversa, y las demás letras de la palabras serán minúsculas si su primera letra es mayúscula, o viceversa
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /primeraLetraYTexto:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando la primera letra de cada palabra
      operationId: cambiarLetra1DemasIgualALetra1
      description: Ajusta el texto modificando la primera letra de cada palabra, pasándola de mayúscula a minúscula o viceversa, y las demás letras de la palabras serán de la misma tipología de la primera letra
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /mayusculasTokenLetras:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando todas las letras a mayúsculas
      operationId: cambiarTodoMayusculasTokenEntreLetras
      description: Ajusta el texto modificando todas las letras a mayúsculas, y entre cada letra escribe el valor del token ingresado
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
        - in: query
          name: token
          description: Valor que se ubicará entre cada letra de cada palabra del texto proporcionado
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /minusculasTokenLetras:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando todas las letras a minúsculas
      operationId: cambiarTodoMinusculasTokenEntreLetras
      description: Ajusta el texto modificando todas las letras a minúsculas, y entre cada letra escribe el valor del token ingresado
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
        - in: query
          name: token
          description: Valor que se ubicará entre cada letra de cada palabra del texto proporcionado
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /mayusculasTokenPalabras:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando todas las letras a mayúsculas
      operationId: cambiarTodoMayusculasTokenEntrePalabras
      description: Ajusta el texto modificando todas las letras a mayúsculas, y entre cada palabra escribe el valor del token ingresado
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
        - in: query
          name: token
          description: Valor que se ubicará entre cada palabra del texto proporcionado
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
  /minusculasTokenPalabras:
    post:
      tags:
        - palabras
      summary: Ajusta el texto modificando todas las letras a minúsculas
      operationId: cambiarTodoMinusculasTokenEntrePalabras
      description: Ajusta el texto modificando todas las letras a minúsculas, y entre cada palabra escribe el valor del token ingresado
      parameters:
        - in: query
          name: palabra
          description: Texto a ser ajustado
          required: true
          schema:
            type: string
        - in: query
          name: token
          description: Valor que se ubicará entre cada palabra del texto proporcionado
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '400':
          description: Error en los parámetros proporcionados
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ObtenerpalabraajustadaResponse'
      x-codegen-request-body-name: body
components:
  schemas:
    ObtenerpalabraajustadaResponse:
      type: object
      properties:
        textoRersultado:
          type: string
tags:
  - name: palabras
    description: Ajuste de palabras del texto